
language: node_js

node_js:
  - "10"

branches:
  only:
    - "dev"

install:
  - npm install -g yarn
  - npm install -g codecov
  - yarn

script:
  - yarn testCoverage

after_success:
  - codecov
  - yarn build

deploy:
  provider: pages
  local-dir: ./docs/
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  on:
    branch: master
