
language: node_js

node_js:
  - "10"

branches:
  only:
    - dev
    - test

install:
  - npm install -g yarn
  - npm install -g codecov
  - yarn

script:
  - yarn testCoverage

after_success:
  - codecov
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  name: $GIT_NAME
  email: $GIT_EMAIL
  target-branch: test
  on: 
    branch: test