
language: node_js

node_js:
  - "10"

branches:
  only:
    - dev

install:
  - npm install -g yarn
  - npm install -g codecov
  - yarn

script:
  - yarn testCoverage

after_success:
  - codecov
  - yarn build

env:
 global:
   - GH_REF: github.com/beef-noodles/PlatformWeb.git

after_script:
  - cd ./docs
  - git init
  - git config user.name "${GIT_NAME}"
  - git config user.email "${GIT_EMAIL}"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GITHUB_TOkEN}@${GH_REF}" test:test